//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agents()
        {
            this.history_sales1 = new HashSet<history_sales>();
        }
    
        public int id { get; set; }
        public int id_type_agents { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<double> phone { get; set; }
        public string logo { get; set; }
        public string adress { get; set; }
        public Nullable<double> priority { get; set; }
        public string director { get; set; }
        public Nullable<double> inn { get; set; }
        public Nullable<double> kpp { get; set; }
        public Nullable<int> id_historysales { get; set; }
    
        public virtual history_sales history_sales { get; set; }
        public virtual type_agent type_agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history_sales> history_sales1 { get; set; }

        public int count { get; set; }
        public int sale { get; set; }
    }
}
