//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public history_sales()
        {
            this.agents = new HashSet<agents>();
        }
    
        public int id { get; set; }
        public int id_product { get; set; }
        public int id_adent { get; set; }
        public Nullable<System.DateTime> data_realize { get; set; }
        public Nullable<double> count_product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agents> agents { get; set; }
        public virtual agents agents1 { get; set; }
        public virtual products products { get; set; }
    }
}
