//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.history_sales = new HashSet<history_sales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_type { get; set; }
        public Nullable<double> article { get; set; }
        public Nullable<int> mans { get; set; }
        public Nullable<double> number_ceha { get; set; }
        public Nullable<double> min_price { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string razmer_ypakovki { get; set; }
        public string ves_bez { get; set; }
        public string ves_s { get; set; }
        public string servificate { get; set; }
        public string num_standart { get; set; }
        public Nullable<int> id_history_product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history_sales> history_sales { get; set; }
        public virtual type_product type_product { get; set; }
    }
}
